### ISSUE TITLE
[Hỏi] download theo list tự tạo, không phải folder

### ISSUE THREAD

**Issue by usphil** [duythongle/fshare2gdrive#12]
Anh cho hỏi mình có list từng file fshare vậy có thể download một lần được không (single phrase chứ không cần parallel). Ví du mình co list như vầy:

https://www.fshare.vn/file/4PYEUUD3ZFVWNA6
https://www.fshare.vn/file/Z5EDCA4IVOFUPO4
https://www.fshare.vn/file/YSQ553NTWT2LIGI
v.v....
Cám ơn anh nhiều lắm. Script này quá tuyệt vời!

**Comment by karasawa-mido** [comment]
Mình giải quyết theo cách này: save từng file fshare vào 1 folder của account của bạn.

**Comment by usphil** [comment]
Vậy phải download rồi upload lên fshare lại thì còn mắc công hơn

> 
> 
> Mình giải quyết theo cách này: save từng file fshare vào 1 folder của account của bạn.
> A Duy Thông cho hỏi có thể download nhiều file cùng 1 lúc không, e làm theo cách của a dùng GNU Parallel nhưng ko chạy dc.

Vậy phải download rồi upload lên fshare lại thì còn mắc công hơn

**Comment by karasawa-mido** [comment]
> Vậy phải download rồi upload lên fshare lại thì còn mắc công hơn
> 
> > Mình giải quyết theo cách này: save từng file fshare vào 1 folder của account của bạn.
> > A Duy Thông cho hỏi có thể download nhiều file cùng 1 lúc không, e làm theo cách của a dùng GNU Parallel nhưng ko chạy dc.
> 
> Vậy phải download rồi upload lên fshare lại thì còn mắc công hơn

Không phải bạn. Lúc vào link fshare có nút "Lưu file về tài khoản" đó. Nhấn vào đó là sẽ copy file về acc của mình.

**Comment by usphil** [comment]
Tôi click vào link file fshare thì IDM nhảy ra download luôn. Disable IDM thi sau khi vào trang download Fshare có thấy "Lưu file về tài khoản" nhưng bị mờ do chưa login. Nhưng vừa login thì nó tự dộng download về không bằng IDM thì cũng bằng web downloader. Bạn có kinh nghiệm về vấn đề này giúp tôi được không?

**Comment by usphil** [comment]
tôi dùng VPS Unmetered Bandwidth 1Gbps nhưng chỉ transfer khoảng 3 tới 6 MBps, plan này giá rẻ $2 1 tháng đầu

**Comment by karasawa-mido** [comment]
Bạn login vào TK fshare => vào phần cài đặt => Thiết lập => Bỏ chọn phần Kích hoạt tải trực tiếp đi. Khi đó sẽ tắt chế độ auto download.

**Comment by usphil** [comment]
Cám ơn bạn nghe, làm được rồi. Nhưng tôi có dung lượng bảo đảm 50GB, không bảo đảm 250GB, mới thử bỏ 1 phim 4K 60GB bị từ chối vì dung lương bảo đảm không đủ

**Comment by usphil** [comment]
Mới mua dung luong 1TB rồi chắc cũng tạm đủ dùng. Cám ơn bạn nghe

**Comment by karasawa-mido** [comment]
Ko có gì bạn. Có thể giải quyết bằng cách bỏ tick chỗ "lưu vào phân vùng đảm bảo". Khi đó acc sẽ save vào phân vùng ko đảm bảo, leech qua drive xong thì xóa, đỡ phải mua thêm dung lượng :D

**Comment by usphil** [comment]
Đúng là  mình hơi hấp tấp, giờ mới thấy dấu check đó!

**Comment by duythongle** [comment]
> Anh cho hỏi mình có list từng file fshare vậy có thể download một lần được không (single phrase chứ không cần parallel). Ví du mình co list như vầy:
> 
> https://www.fshare.vn/file/4PYEUUD3ZFVWNA6
> https://www.fshare.vn/file/Z5EDCA4IVOFUPO4
> https://www.fshare.vn/file/YSQ553NTWT2LIGI
> v.v....
> Cám ơn anh nhiều lắm. Script này quá tuyệt vời!

Bạn có thể dùng lệnh xargs. Ví dụ:

1. Để cho gọn code, đầu tiên tạo alias
```bash
echo "alias f2g='curl -sS https://raw.githubusercontent.com/duythongle/fshare2gdrive/master/fshare2gdrive.js | tail -n+2 | node -'" >> ~/.bashrc
```
2. Tạo file `fshare_links.txt` chứa danh sách các link fshare (link fshare file/folder đều được).
3. Chạy lệnh
```bash
cat fshare_links.txt | xargs -I % bash -cil 'f2g "%" "<your-rclone-drive>" "</path/to/your/remote/folder> | bash -s"'
```
> Nhớ thay `<your-rclone-drive>` và `</path/to/your/remote/folder>` tương ứng
> Chú ý nhập đủ các dấu nháy đơn và kép
> Tiện hơn thì bạn cứ copy&paste rồi thay các tham số tương ứng vào

**Comment by duythongle** [comment]
> Mình giải quyết theo cách này: save từng file fshare vào 1 folder của account của bạn.
> A Duy Thông cho hỏi có thể download nhiều file cùng 1 lúc không, e làm theo cách của a dùng GNU Parallel nhưng ko chạy dc.

Bạn cứ copy&paste lệnh chạy và output lỗi trong console lên đây. Chú ý là do GDrive cho tạo thư mục trùng tên (weird!) nên **KHÔNG** khuyến khích upload fshare folder song song bằng GNU Parallel nhé.

**Comment by duythongle** [comment]
> tôi dùng VPS Unmetered Bandwidth 1Gbps nhưng chỉ transfer khoảng 3 tới 6 MBps, plan này giá rẻ $2 1 tháng đầu

Đúng r, nghẽn do fshare giới hạn download speed mỗi connection 3-6Mb/s. Muống download nhanh bạn phải dùng lệnh download song song nhiều connection như aria2, axel download cả file về máy. Xong dùng rclone upload lên gdrive.

**Comment by vinhvgs** [comment]
> > tôi dùng VPS Unmetered Bandwidth 1Gbps nhưng chỉ transfer khoảng 3 tới 6 MBps, plan này giá rẻ $2 1 tháng đầu
> 
> Đúng r, nghẽn do fshare giới hạn download speed mỗi connection 3-6Mb/s. Muống download nhanh bạn phải dùng lệnh download song song nhiều connection như aria2, axel download cả file về máy. Xong dùng rclone upload lên gdrive.

Bạn ơi. Hình như đang lỗi cái api v3.
Với cả bạn cho mình hỏi có cách nào check những file đã get trên gdrive rồi sẽ bỏ qua k get lại những file đó nữa không b? Tại có nhiều folder đang get thì lỗi thành ra để lọc những file chưa get quá mất thời gian hoặc get đè file đã có rồi cũng vậy

**Comment by duythongle** [comment]
@vinhvgs Script chỉ cố gắng làm tốt tính năng getlink và transfer. Còn lại, bạn phải tự quản lý nội dung GDrive của bạn. Good news là rclone có hỗ trợ cờ bỏ qua file trùng theo một số tiêu chí nhất định như `-c`, `-u`... xem thêm [https://rclone.org/flags/](https://rclone.org/flags/)

**Comment by vinhvgs** [comment]
> Còn lại,

Cảm ơn bạn. Mình là dân ngoài ngành nên k rõ vấn đề này. Nhìn các lệnh còn hoa hết mắt rồi :D 
Nhìn bạn chỉ thế kia mình còn chả biết để mấy cái -c -u ở đâu ý

**Comment by usphil** [comment]
> Bạn có thể dùng lệnh xargs. Ví dụ:

Dùng list tự tạo hay hơn folder fshare rất nhiều mà bửa giờ mới làm được. Cám ơn duythongle rất nhiều!

**Comment by tienhuy170893** [comment]
@duythongle có cách nào tải nhiều file 1 lúc ko bạn ơi vì fshare giới hạn tải từng file nên nếu có thì chỉ mình với cảm ơn nhiều

**Comment by dieptu2** [comment]
Anh Thông cho em hỏi em bị lỗi như ảnh thì fix sao ạ 

![19DE05A6-344B-4EEA-A1CC-C91225ACFCF8](https://user-images.githubusercontent.com/65355677/87949343-199dc600-cad0-11ea-92ca-faf7f7537288.png)

**Comment by hiepute** [comment]
> > Mình giải quyết theo cách này: save từng file fshare vào 1 folder của account của bạn.
> > A Duy Thông cho hỏi có thể download nhiều file cùng 1 lúc không, e làm theo cách của a dùng GNU Parallel nhưng ko chạy dc.
> 
> Bạn cứ copy&paste lệnh chạy và output lỗi trong console lên đây. Chú ý là do GDrive cho tạo thư mục trùng tên (weird!) nên **KHÔNG** khuyến khích upload fshare folder song song bằng GNU Parallel nhé.

Chào anh, 
Hiện tại em đang gặp 1 lỗi như bên dưới khi chạy lệnh và nó chỉ bắt được link cuối cùng trong list fshare_links.txt và tiến hành transfer
`cat fshare_links.txt | xargs -I % bash -cil 'f2g "%" "<your-rclone-drive>" "</path/to/your/remote/folder>" | bash -s'`

`(node:22552) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22583) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22583) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22583) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22619) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22619) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22649) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22649) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22685) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22715) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22745) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22781) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22811) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22841) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22877) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Danh sách link trong file fshare_links.txt

> ``
https://www.fshare.vn/folder/RAU3MKRVT9F6
https://www.fshare.vn/folder/12YERGNN2ZLN
https://www.fshare.vn/folder/LF1KKVGBYKOH
https://www.fshare.vn/folder/K4MKM7VHHPW2
https://www.fshare.vn/folder/BJFC4BYMVCQH
https://www.fshare.vn/folder/P7IPP8QRAT3M
https://www.fshare.vn/folder/YMYQFNRKBMU6
https://www.fshare.vn/folder/F8L3B38M7TAN
https://www.fshare.vn/folder/NN23ZI7773KD
https://www.fshare.vn/folder/BA6TCYKN8YU3
https://www.fshare.vn/folder/L6UE7IPSK6WS
https://www.fshare.vn/folder/4ASTITD43WYT
>

**Comment by NgTrThanh** [comment]
> @vinhvgs Script chỉ cố gắng làm tốt tính năng getlink và transfer. Còn lại, bạn phải tự quản lý nội dung GDrive của bạn. Good news là rclone có hỗ trợ cờ bỏ qua file trùng theo một số tiêu chí nhất định như `-c`, `-u`... xem thêm https://rclone.org/flags/

Nếu dùng lênh rcat thì không có cách nào với mấy flag?

rclone rcat

**If the remote file already exists, it will be overwritten.**

**Comment by docongtoanh** [comment]
dùng với list link thì dc mà list folder ko dc ạ 
báo lỗi :UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at genCmd ([stdin]:204:59)
    at [stdin]:246:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:76943) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:76943) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:76967) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
